openapi: 3.0.0
info:
  title: Training Microservice API
  description: Backend API to control the Home automation stack
  version: 2.0.0
servers:
  - url: /{{base_path_prefix}}/api/{{api_version}}
    description: Base URL
  - url: /
    description: Auxiliary URL

components:
  schemas:
    Entry:
      properties:
        key:
          type: string
        value:
          type: string


paths:
  /:
    get:
      operationId: api.default.hello_world
      summary: Returns the Hello World Message
      description: Possible liveness check
      responses:
        '200':
          description: Greets you in a polite manner
  /entry:
    get:
      operationId: api.default.get_entries
      summary: Returns all entries
      description: Get all cached entries
      responses:
        '200':
          description: you got it
          content:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Entry'
  /entry/search:
    get:
      operationId: api.default.search_entries
      summary: search for an entry
      description: search for a cached entry
      parameters:
        - in: query
          name: regex_str
          schema:
            type: string
          required: true
      responses:
        '200':
          description: you got it
          content:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Entry'